@hostname = http://localhost:3001
@content-type = application/json


GET {{hostname}}

### Post Webtoon
POST {{hostname}}/webtoon HTTP/1.1
Content-Type: {{content-type}}

        {
            "title": "생각하는 정이",
            "publisher": "Bufftoon",
            "toon": "completed",
            "author": "정이",
            "genre": "드라마",
            "image": "https://buffimgs.plaync.com/buff/contents/0/10077/cover_8a2ec7727edff4ccde40b373faaed32f5e40e3e32e3a13e6570325f883529f91.jpg",
            "url": "https://bufftoon.plaync.com/series/10077",
            "age": "",
            "days": "기타A"
        }

### Post a Comment
POST {{hostname}}/comment HTTP/1.1
Content-Type: {{content-type}}

{
    "comment": "Goodbye world!",
    "username": "CarrotCake",
    "email":"carrot@gmail.com",
    "postId": "sample"
}

###
DELETE {{hostname}}/comment/61cc773b1516b09d7963160b HTTP/1.1
Content-Type: {{content-type}}

### Get Webtoon
GET  {{hostname}}/webtoon/아비무쌍 HTTP/1.1
Content-Type: {{content-type}}

### Get Webtoons Pagination
GET  {{hostname}}/webtoon?page=1&limit=10 HTTP/1.1
Content-Type: {{content-type}}

### Get Webtoons Pagination/tab
GET  {{hostname}}/webtoon?page=1&limit=10&toon=ongoing HTTP/1.1
Content-Type: {{content-type}}

### Get Comments
GET  {{hostname}}/comment/ HTTP/1.1
Content-Type: {{content-type}}

### Post signup
POST {{hostname}}/signup HTTP/1.1
Content-Type: {{content-type}}

{
    "username": "TomatoSauce",
    "email": "111@gmail.com",
    "password": "123123123q",
    "confirmPassword": "123123123q"
}

### Post login
POST {{hostname}}/login HTTP/1.1
Content-Type: {{content-type}}

{
    "email": "111@gmail.com",
    "password": "123123123q"
}