export const BannerArray = [
    {
        url: "https://thumbs.dreamstime.com/b/christmas-banner-gingerbread-man-cookies-mulled-wine-holiday-decorations-fir-branches-festive-bokeh-lighting-dark-80838264.jpg",
        text: "웹툰모아는 비영리 웹사이트입니다. (1/4)",
    },
    {
        url: "https://thumbs.dreamstime.com/b/xmas-banner-204671559.jpg",
        text: "모든 웹툰은 공식 사이트로 연결되어 있습니다. (2/4)",
    },
    {
        url: "https://thumbs.dreamstime.com/b/christmas-holidays-banner-tree-bokeh-background-gifts-lights-wooden-floor-161932746.jpg",
        text: "광고용 칸 아닙니다. 배너는 연습삼아 만들어 봤습니다. 화살표 클릭하면 멈춥니다. (3/4)",
    },
    {
        url: "https://thumbs.dreamstime.com/z/merry-christmas-colorful-balls-banner-decoration-stars-backgroun-background-text-77218307.jpg",
        text: "메리 크리스마스 (4/4)",
    },
];

export const categoryTab = ["일반", "정보", "공유", "요청", "질문", "후기"];
export const categoryArray = [
    { name: "전체", url: "" },
    { name: "공지", url: "?category=공지" },
    { name: "일반", url: "?category=일반" },
    { name: "정보", url: "?category=정보" },
    { name: "공유", url: "?category=공유" },
    { name: "요청", url: "?category=요청" },
    { name: "질문", url: "?category=질문" },
    { name: "후기", url: "?category=후기" },
];

export const GnbArray = [
    {
        id: 0,
        name: "연재중",
        url: "webtoon?category=ongoing",
        type: "TAB_ONGOING",
    },
    {
        id: 1,
        name: "완결",
        url: "webtoon?category=completed",
        type: "TAB_COMPLETED",
    },
    { id: 2, name: "성인", url: "webtoon?category=adult", type: "TAB_ADULT" },
    // { id: 3, name: "BL/GL", url: "webtoon?toon=bl%2Fgl", type: "TAB_BLGL" },
    { id: 4, name: "My", url: "user", type: "TAB_MY" },
    { id: 5, name: "커뮤니티", url: "community", type: "TAB_COMMUNITY" },
];

export const RecWebtoonArray = [
    {
        _id: 1,
        title: "1초",
        toon: "ongoing",
        publisher: "Naver",
        author: "시니 / 광운",
        genre: "스토리, 드라마",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/725586/thumbnail/thumbnail_IMAG06_94506834-c312-4ad9-a704-996570d0c6fc.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=725586",
        age: "전체",
        days: "금",
    },
    {
        _id: 2,
        title: "쌉니다 천리마마트 ",
        toon: "completed",
        publisher: "Naver",
        author: "김규삼",
        genre: "스토리, 개그",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/697679/thumbnail/thumbnail_IMAG06_9a844df7-d7ef-4ce9-9bcd-84254976f4b6.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=697679",
        age: "전체",
        days: "완결",
    },
    {
        _id: 3,
        title: "쌉니다 천리마마트 ",
        toon: "completed",
        publisher: "Naver",
        author: "김규삼",
        genre: "스토리, 개그",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/697679/thumbnail/thumbnail_IMAG06_9a844df7-d7ef-4ce9-9bcd-84254976f4b6.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=697679",
        age: "전체",
        days: "완결",
    },
    {
        _id: 4,
        title: "쌉니다 천리마마트 ",
        toon: "completed",
        publisher: "Naver",
        author: "김규삼",
        genre: "스토리, 개그",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/697679/thumbnail/thumbnail_IMAG06_9a844df7-d7ef-4ce9-9bcd-84254976f4b6.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=697679",
        age: "전체",
        days: "완결",
    },
    {
        _id: 5,
        title: "쌉니다 천리마마트 ",
        toon: "completed",
        publisher: "Naver",
        author: "김규삼",
        genre: "스토리, 개그",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/697679/thumbnail/thumbnail_IMAG06_9a844df7-d7ef-4ce9-9bcd-84254976f4b6.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=697679",
        age: "전체",
        days: "완결",
    },
    {
        _id: 6,
        title: "쌉니다 천리마마트 ",
        toon: "completed",
        publisher: "Naver",
        author: "김규삼",
        genre: "스토리, 개그",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/697679/thumbnail/thumbnail_IMAG06_9a844df7-d7ef-4ce9-9bcd-84254976f4b6.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=697679",
        age: "전체",
        days: "완결",
    },
    {
        _id: 7,
        title: "쌉니다 천리마마트 ",
        toon: "completed",
        publisher: "Naver",
        author: "김규삼",
        genre: "스토리, 개그",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/697679/thumbnail/thumbnail_IMAG06_9a844df7-d7ef-4ce9-9bcd-84254976f4b6.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=697679",
        age: "전체",
        days: "완결",
    },
    {
        _id: 8,
        title: "쌉니다 천리마마트 ",
        toon: "completed",
        publisher: "Naver",
        author: "김규삼",
        genre: "스토리, 개그",
        image: "https://shared-comic.pstatic.net/thumb/webtoon/697679/thumbnail/thumbnail_IMAG06_9a844df7-d7ef-4ce9-9bcd-84254976f4b6.jpg",
        url: "https://comic.naver.com/webtoon/list?titleId=697679",
        age: "전체",
        days: "완결",
    },
];
